# Generated by Django 5.1.6 on 2025-02-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='img',
            new_name='image',
        ),
    ]
